/** Tailwind config — the EXACT Stitch "Soft Landing" theme tokens
 *  (ported from the Stitch screens' tailwind.config so the markup drops in 1:1).
 */
import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#673b30",
        "secondary-container": "#ffc0b0",
        "primary-fixed-dim": "#a5d0be",
        "surface-variant": "#d3e5f5",
        "surface-container-low": "#eaf5ff",
        "surface-container-high": "#d8ebfa",
        "on-primary-fixed-variant": "#264e41",
        "primary-container": "#8fb9a8",
        outline: "#717975",
        "inverse-on-surface": "#e5f2ff",
        primary: "#3e6658",
        "on-surface-variant": "#414845",
        "on-secondary": "#ffffff",
        "surface-tint": "#3e6658",
        "primary-fixed": "#c0ecda",
        "tertiary-fixed-dim": "#accbe0",
        "tertiary-fixed": "#c7e7fd",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        tertiary: "#446275",
        "inverse-surface": "#21323e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#284658",
        "surface-bright": "#f6faff",
        "secondary-fixed-dim": "#f6b8a8",
        "on-tertiary-fixed": "#001e2d",
        "surface-dim": "#cadcec",
        "outline-variant": "#c0c8c3",
        "on-primary": "#ffffff",
        surface: "#f6faff",
        "on-surface": "#0b1d29",
        "on-tertiary-fixed-variant": "#2c4a5c",
        "on-primary-fixed": "#002117",
        "on-primary-container": "#224a3d",
        "on-background": "#0b1d29",
        secondary: "#825246",
        "secondary-fixed": "#ffdbd1",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        background: "#f6faff",
        "on-secondary-container": "#7b4c40",
        "on-secondary-fixed": "#331108",
        "inverse-primary": "#a5d0be",
        "surface-container-highest": "#d3e5f5",
        "tertiary-container": "#96b4c9",
        "surface-container": "#dff0ff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        sm: "12px",
        xl: "80px",
        gutter: "24px",
        base: "8px",
        md: "24px",
        xs: "4px",
        lg: "48px",
      },
      fontFamily: {
        "headline-xl": ["Assistant", "Noto Sans Hebrew", "sans-serif"],
        "headline-lg": ["Assistant", "Noto Sans Hebrew", "sans-serif"],
        "headline-md": ["Assistant", "Noto Sans Hebrew", "sans-serif"],
        "body-md": ["Assistant", "Noto Sans Hebrew", "sans-serif"],
        "label-md": ["Assistant", "Noto Sans Hebrew", "sans-serif"],
        "label-sm": ["Assistant", "Noto Sans Hebrew", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [forms],
};
